file:
    upload-dir: /home/ubuntu/upload
logging:
    file:
        name: /logs/lotteon.log
    level:
        org:
            hibernate:
                orm:
                    jdbc:
                        bind: info
                sql: debug
            mybatis: error
            springframework:
                security: debug
                web: error
        root: info
server:
    error:
        whitelabel:
            enabled: false
    port: 8080
spring:
    config :
#        import :
#            - optional:classpath:application-ec2.yml
#            - classpath:application-local.yml
        import:
            - optional:classpath:application-local.yml
            - classpath:application-ec2.yml



#    application:
#        name: lotteon
#        version: 0.0.1-SNAPSHOT
#    cache:
#        type: redis
#    servlet:
#        multipart:
#            max-file-size: 10MB
#            max-request-size: 10MB
#    thymeleaf:
#        cache: false
#        check-template-location: true
#        enabled: true
#        mode: HTML
#        prefix: classpath:/templates/
#        suffix: .html
