
server:
    error:
        whitelabel:
            enabled: false
    port: 8080
spring:
    config :
        import:
            - optional:classpath:application-local.yml
            - classpath:application-ec2.yml


